PILHA	SEGMENT
	DW 1024 dup(?)
PILHA	ENDS

DADOS	SEGMENT
MENS	DB 'Ola mundo! Esse foi meu primeiro programa em Assembler...',13,10,'$'
DADOS 	ENDS

COD	SEGMENT
	ASSUME CS: COD, SS:PILHA, DS:DADOS

INI:	MOV AX,DADOS
	MOV DS,AX
	MOV AX,PILHA
	MOV SS,AX
	MOV CX,100
LOOP0:	LEA DX,MENS
	MOV AH,9
	INT 21H
	LOOP LOOP0
	MOV AH,4CH	;PEDE AO DOS PARA TERMINAR
	INT 21H	

COD	ENDS

END	INI